CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(50)
);

CREATE TABLE seila (
    id INT AUTO_INCREMENT PRIMARY KEY,
    oi VARCHAR(255),
    la VARCHAR(50)
);